# Generated by Django 3.2.4 on 2021-06-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0002_rename_shoes_shoe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='code',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='title',
        ),
        migrations.AddField(
            model_name='shoe',
            name='brand',
            field=models.CharField(choices=[(0, 'Adidas'), (1, 'Converse'), (2, 'Nike'), (3, 'Puma')], default='Nike', max_length=100),
        ),
        migrations.AddField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shoe',
            name='sizes',
            field=models.CharField(choices=[(0, '8'), (1, '9'), (2, '10'), (3, '11'), (4, '12')], default='10', max_length=100),
        ),
    ]
