# Generated by Django 3.2.4 on 2021-06-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0003_auto_20210627_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
        ),
    ]
