# Generated by Django 3.2.4 on 2021-06-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0004_alter_shoe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='sizes',
            field=models.CharField(default='8,9,10,11,12', max_length=100),
        ),
    ]
