# Generated by Django 3.2.4 on 2021-06-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0005_alter_shoe_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.CharField(default='No Name', max_length=100)),
                ('shoe_id', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('size', models.CharField(default='8,9,10,11,12', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(choices=[('Adidas', 'Adidas'), ('Converse', 'Converse'), ('Nike', 'Nike'), ('Puma', 'Puma')], default='Nike', max_length=100),
        ),
    ]
