# Generated by Django 3.2.4 on 2021-06-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0007_alter_order_shoe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='poster',
            field=models.CharField(default='', max_length=100),
        ),
    ]
