# Generated by Django 3.2.4 on 2021-06-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0008_shoe_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='sizes',
            new_name='size',
        ),
    ]
