# Generated by Django 3.2.4 on 2021-06-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0009_rename_sizes_shoe_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='size',
            new_name='sizes',
        ),
    ]
