# Generated by Django 3.2.4 on 2021-06-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0010_rename_size_shoe_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shoe_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='No Address', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
