# Generated by Django 3.2.4 on 2021-06-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0011_auto_20210630_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.CharField(default='Empty', max_length=5000),
        ),
    ]
